import type { Assignment, Backup, Shortfall, SchedulingRun } from '../../../shared/domain.js';
import type { ScheduleResult, SchedulerInput } from './scheduler.js';
import { scheduleSessions } from './scheduler.js';
import { SchedulingPublicationError, SchedulingStore } from '../publication.js';

/**
 * FROZEN pre-optimization orchestration — the parity oracle for
 * `accelerate-schedule-preview`.
 *
 * A verbatim copy of `runScheduling` from `src/server/scheduling/publication.ts`
 * as of the baseline commit, pointed at the frozen reference scheduler. The
 * staged publication boundary itself (`SchedulingStore`) is deliberately *not*
 * frozen: it is shared, deterministic bookkeeping that both implementations run
 * through, so a difference in the staged rows can only come from the scheduler
 * under test. Not imported by any production entry point.
 *
 * Do not edit this file except to mirror an intentional, evidence-backed change
 * to the live `runScheduling` orchestration, and never without re-recording the
 * baseline parity digests.
 */

export type ReferenceRunInput = Omit<SchedulerInput, 'asOf'> & {
  inputRevision: number;
  actorId?: string;
  source?: string;
  runId?: string;
  startedAt?: string;
};

export type ReferenceRunResult = {
  run: SchedulingRun;
  calculation: ScheduleResult;
  /** Published rows as `publishRun` returned them, with the staged revision attached. */
  assignments: Assignment[];
  backups: Backup[];
  shortfalls: Shortfall[];
  revision: number;
};

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** Compute, stage, and publish exactly one complete scheduling revision. */
export function runReferenceScheduling(
  store: SchedulingStore,
  input: ReferenceRunInput
): ReferenceRunResult {
  return store.withSchedulingLock(() => {
    const run = store.beginRun(input.inputRevision, input.runId, input.startedAt);
    try {
      const schedulerInput: SchedulerInput = {
        volunteers: input.volunteers,
        sessions: input.sessions,
        // The run start is the deterministic cutoff for both the calculation
        // and the persisted run metadata. A session starting at this exact
        // instant is already started and is therefore excluded.
        asOf: run.startedAt,
        scheduleRevision: store.currentRevision() + 1
      };
      if (input.schedulingTimeZone !== undefined) schedulerInput.schedulingTimeZone = input.schedulingTimeZone;
      if (input.exceptions !== undefined) schedulerInput.exceptions = input.exceptions;
      if (input.availabilityExceptions !== undefined) schedulerInput.availabilityExceptions = input.availabilityExceptions;
      if (input.assignments !== undefined) schedulerInput.assignments = input.assignments;
      if (input.currentAssignments !== undefined) schedulerInput.currentAssignments = input.currentAssignments;
      if (input.existingAssignments !== undefined) schedulerInput.existingAssignments = input.existingAssignments;
      if (input.startedAt !== undefined) schedulerInput.createdAt = input.startedAt;
      const calculation = scheduleSessions(schedulerInput);
      const staged = store.stageRun(run.id, calculation);
      const published = store.publishRun(run.id);
      const completed = store.run(run.id);
      if (!completed || !staged.outputRevision) {
        throw new SchedulingPublicationError('INTERNAL_ERROR', 'Scheduling publication did not produce a completed run');
      }
      return { run: completed, calculation, assignments: published.assignments, backups: published.backups, shortfalls: published.shortfalls, revision: published.revision };
    } catch (error) {
      store.failRun(run.id, errorMessage(error));
      throw error;
    }
  });
}
